<?php


class TBridge{
    public function __construct(){
    }

    public function __destruct(){
    }
}


class TFileDownBridge extends TBridge
{
    private $APP_UPLOAD_PATH = $_SERVER['DOCUMENT_ROOT']."/upload/appupload/";
    private $CUSOMER_APP_UPLOAD_URL = "https://customer.banjjakpet.com/upload/appupload/";
    private $fileName;

    public function __construct($fileName)
    {
        parent::__construct();
        $this->fileName = $fileName;
    }

    public function __destruct(){
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function fileDownload(){
        $local_file = $this->APP_UPLOAD_PATH.$this->fileName;
        //$remote_file = $this->CUSOMER_APP_UPLOAD_URL.$this->fileName;
        $remote_file = $this->CUSOMER_APP_UPLOAD_URL."fcppt_20220515238584.jpg";
        if(!file_exists($local_file)){
            $options = array(
                CURLOPT_FILE    => fopen($local_file, 'w'),
                CURLOPT_TIMEOUT =>  28800, // set  8 hours
                CURLOPT_URL     => $remote_file
            );

            $ch = curl_init();
            curl_setopt_array($ch, $options);
            curl_exec($ch);
            curl_close($ch);
            if(file_exists($local_file)){
                return true;
            }else{
                return false;
            }
        }
        return true;
    }
}